import { LanguageTexts } from '../models/types';

export const languages: { [key: string]: LanguageTexts } = {
    'zh-CN': {
        sitReminderTitle: '🚶‍♂️ 该起身活动了！',
        sitReminderMessage: '长时间坐着对健康不利，起来伸展一下身体，活动活动筋骨吧！',
        sitReminderButton: '我已经起身活动了',
        drinkReminderTitle: '💧 该喝水了！',
        drinkReminderMessage: '保持身体水分充足很重要，现在就喝一杯水吧！',
        drinkReminderButton: '我已经喝水了',
        confirmMessage: '提醒已确认，计时器已重置',
        resetMessage: '所有计时器已重置',
        statusTitle: '📊 健康提醒状态',
        sitStatus: '🚶‍♂️ 久坐提醒',
        drinkStatus: '💧 喝水提醒',
        disabled: '已禁用',
        minutesLater: '分钟后提醒',
        comingSoon: '即将提醒',
        waitSeconds: '请等待',
        snoozeButton: '稍后提醒（5分钟）',
        gentleReminder: '温馨提示',
        urgentReminder: '重要提醒',
        historyTitle: '📊 健康提醒历史',
        todayStats: '今日统计',
        weekStats: '本周统计',
        totalSit: '起身次数',
        totalDrink: '喝水次数',
        workTime: '工作时长',
        noHistory: '暂无历史记录',
        viewHistory: '查看历史记录',
        viewDashboard: '查看健康仪表盘',
        focusModeActive: '专注模式',
        focusModeEnded: '专注模式已结束，提醒已恢复',
        focusModeStarted: '专注模式已启动，将持续',
        focusModeRemaining: '剩余时间',
        enterFocusMode: '进入专注模式',
        exitFocusMode: '退出专注模式',
        focusModePrompt: '请输入专注时长（分钟，1-480）',
    },
    en: {
        sitReminderTitle: '🚶‍♂️ Time to Stand Up!',
        sitReminderMessage:
            'Sitting for long periods is bad for your health. Get up, stretch your body, and move around!',
        sitReminderButton: 'I have stood up and moved',
        drinkReminderTitle: '💧 Time to Drink Water!',
        drinkReminderMessage: 'Staying hydrated is important for your health. Drink a glass of water now!',
        drinkReminderButton: 'I have drunk water',
        confirmMessage: 'Reminder confirmed, timer has been reset',
        resetMessage: 'All timers have been reset',
        statusTitle: '📊 Health Reminder Status',
        sitStatus: '🚶‍♂️ Sit Reminder',
        drinkStatus: '💧 Drink Reminder',
        disabled: 'Disabled',
        minutesLater: 'minutes until reminder',
        comingSoon: 'Coming soon',
        waitSeconds: 'Please wait',
        snoozeButton: 'Snooze (5 minutes)',
        gentleReminder: 'Gentle Reminder',
        urgentReminder: 'Urgent Reminder',
        historyTitle: '📊 Health Reminder History',
        todayStats: 'Today Stats',
        weekStats: 'Week Stats',
        totalSit: 'Stand Up Count',
        totalDrink: 'Drink Count',
        workTime: 'Work Time',
        noHistory: 'No history yet',
        viewHistory: 'View History',
        viewDashboard: 'View Health Dashboard',
        focusModeActive: 'Focus Mode',
        focusModeEnded: 'Focus mode ended, reminders resumed',
        focusModeStarted: 'Focus mode started, duration:',
        focusModeRemaining: 'Remaining',
        enterFocusMode: 'Enter Focus Mode',
        exitFocusMode: 'Exit Focus Mode',
        focusModePrompt: 'Enter focus duration (minutes, 1-480)',
    },
};
